### ISSUE TITLE
License? Version? Makefile?

### ISSUE THREAD

**Issue by ghost** [limiteci/donut.c#2]
Hi, I've seen this 3d spinning donut used in some screenshots in https://old.reddit.com/r/unixporn, super cool!

I'd like to package this but it needs at least a license and preferably a versioned release and a simple makefile would be helpful.

**Comment by Zipdox2** [comment]
```make
CC=gcc
LIBS=-lm
OPTS=-w
TARGET=donut

all: $(TARGET)

$(TARGET): donut.c
	$(CC) -o $@ $^ $(LIBS) $(OPTS)

clean:
	rm $(TARGET)
```

**Comment by ghost** [comment]
Closing as stale.
